In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from tensorflow.python.keras import models, layers, optimizers
import tensorflow
from tensorflow.keras.preprocessing.text import Tokenizer, text_to_word_sequence
from tensorflow.keras.preprocessing.sequence import pad_sequences
import bz2
from sklearn.metrics import f1_score, roc_auc_score, accuracy_score
import re


%matplotlib inline

In [2]:
#Creating a function to load the text and labels from train and set

In [3]:
def get_labels_and_texts(file):
    labels = []
    texts = []
    for line in bz2.BZ2File(file):
        x = line.decode("utf-8")
        labels.append(int(x[9])-1)
        texts.append(x[10:].strip())
    return np.array(labels),texts 
train_labels, train_texts = get_labels_and_texts('train.ft.txt.bz2')
test_labels, test_texts = get_labels_and_texts('test.ft.txt.bz2')

In [4]:
train_labels[0]

1

In [5]:
train_texts[0]

'Stuning even for the non-gamer: This sound track was beautiful! It paints the senery in your mind so well I would recomend it even to people who hate vid. game music! I have played the game Chrono Cross but out of all of the games I have ever played it has the best music! It backs away from crude keyboarding and takes a fresher step with grate guitars and soulful orchestras. It would impress anyone who cares to listen! ^_^'

In [6]:
train_labels=train_labels[0:500]

In [7]:
train_texts=train_texts[0:500]

In [9]:
import re
NON_ALPHANUM = re.compile(r'[\W]')
NON_ASCII = re.compile(r'[^a-z0-1\s]')
def normalize_texts(texts):
    normalized_texts = []
    for text in texts :
        lower = text.lower()
        no_punctuation = NON_ALPHANUM.sub(r' ',lower)
        no_non_ascii = NON_ASCII.sub(r'',no_punctuation)
        normalized_texts.append(no_non_ascii)
    return normalized_texts
train_texts = normalize_texts(train_texts)
test_texts = normalize_texts(test_texts)

In [10]:
train_texts[0]

'stuning even for the non gamer  this sound track was beautiful  it paints the senery in your mind so well i would recomend it even to people who hate vid  game music  i have played the game chrono cross but out of all of the games i have ever played it has the best music  it backs away from crude keyboarding and takes a fresher step with grate guitars and soulful orchestras  it would impress anyone who cares to listen    '

In [11]:
#countvectorizer


In [12]:
import pickle
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(binary=True)
cv.fit(train_texts)
x=cv.transform(train_texts)
x_test = cv.transform(test_texts)
pickle.dump(cv, open("vector.pickel", "wb"))


In [13]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split


x_train,x_val, y_train, y_val = train_test_split(x,train_labels, train_size=0.75)


for c in [0.01, 0.05, 0.25, 0.5, 1]:
    Ir = LogisticRegression(C=c)
    Ir.fit(x_train,y_train)
    print("Accuracy for C=%s: %s" % (c,accuracy_score(y_val,Ir.predict(x_val))))

Accuracy for C=0.01: 0.72
Accuracy for C=0.05: 0.768
Accuracy for C=0.25: 0.784
Accuracy for C=0.5: 0.8
Accuracy for C=1: 0.8


In [14]:
#final model
Ir = LogisticRegression(C=0.5)
Ir.fit(x_train,y_train)
print("Accuracy for C=%s: %s" % (0.5,accuracy_score(y_val,Ir.predict(x_val))))
pickle.dump(Ir, open('model.pkl', 'wb'))

Accuracy for C=0.5: 0.8


In [15]:
Ir.predict(x_test[2])

array([0])

In [16]:
test_labels[2]

0

In [17]:
test_texts[2]


'batteries died within a year      i bought this charger in jul 00 and it worked ok for a while  the design is nice and convenient  however  after about a year  the batteries would not hold a charge  might as well just get alkaline disposables  or look elsewhere for a charger that comes with batteries that have better staying power '

In [18]:
import csv
filename = "chrome_reviews.csv"
ls = []
ts = []
rw= []
file = open(filename, encoding="utf8")
csvreader = csv.reader(file)
fields = next(csvreader)
for row in csvreader:
    ls.append(row[3])
    rw.append(row[2].strip())
ts = normalize_texts(rw)
x_t = cv.transform(ts)
Ir.predict(x_t[2])



array([0])

In [21]:
ts[2]

'not able to update  neither able to uninstall '

In [19]:
vectorizer = pickle.load(open("vector.pickel", "rb"))
loaded_model = pickle.load(open("model.pkl", "rb"))
loaded_model.predict(vectorizer.transform([ts[2]]))

array([0])

In [49]:
k=''
k=Ir.predict(x_t[2])

print(type(k))

<class 'numpy.ndarray'>


In [20]:
arr = np.array([1])
for i in range(100):
    if row[3] in {'1','2'} and Ir.predict(x_t[i]) == arr :
        print(row[2])

After update it lag and always slow same goes to googleee ;)))))) !!!! I want to do my work but 🌚
After update it lag and always slow same goes to googleee ;)))))) !!!! I want to do my work but 🌚
After update it lag and always slow same goes to googleee ;)))))) !!!! I want to do my work but 🌚
After update it lag and always slow same goes to googleee ;)))))) !!!! I want to do my work but 🌚
After update it lag and always slow same goes to googleee ;)))))) !!!! I want to do my work but 🌚
After update it lag and always slow same goes to googleee ;)))))) !!!! I want to do my work but 🌚
After update it lag and always slow same goes to googleee ;)))))) !!!! I want to do my work but 🌚
After update it lag and always slow same goes to googleee ;)))))) !!!! I want to do my work but 🌚
After update it lag and always slow same goes to googleee ;)))))) !!!! I want to do my work but 🌚
After update it lag and always slow same goes to googleee ;)))))) !!!! I want to do my work but 🌚
After update it lag 